### ISSUE TITLE
Cura 3.2 Beta cant deselect "Show Webcam"

### ISSUE THREAD

**Issue by SphaeroX** [fieldOfView/OctoPrintPlugin#68]
When i try to deselect "show webcam" Cura will crash:

```
 Traceback (most recent call last):
  File "C:\Users\MGasc\AppData\Roaming\cura\3.2\plugins\OctoPrintPlugin\DiscoverOctoPrintAction.py", line 202, in setContainerMetaDataEntry
    containers = ContainerRegistry.getInstance().findContainers(None, id = container_id)
TypeError: findContainers() takes 1 positional argument but 2 were given
```

```
`Thread 0x00000f40 (most recent call first):
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Backend\Backend.py", line 155 in _storeStderrToLogThread
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00003190 (most recent call first):
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Backend\Backend.py", line 147 in _storeOutputToLogThread
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x0000093c (most recent call first):
  File "threading.py", line 297 in wait
  File "zeroconf.py", line 1569 in wait
  File "zeroconf.py", line 1153 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00001c54 (most recent call first):
  File "threading.py", line 297 in wait
  File "zeroconf.py", line 1569 in wait
  File "zeroconf.py", line 1017 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x000004a4 (most recent call first):
  File "zeroconf.py", line 946 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x000008e4 (most recent call first):
  File "D:\Programme\Cura\Ultimaker Cura 3.2\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 86 in _updateThread
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00001c90 (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 116 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00001ad8 (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 116 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x0000422c (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 116 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x0000325c (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 116 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00002b94 (most recent call first):
  File "threading.py", line 297 in wait
  File "zeroconf.py", line 1569 in wait
  File "zeroconf.py", line 1153 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00002428 (most recent call first):
  File "threading.py", line 297 in wait
  File "zeroconf.py", line 1569 in wait
  File "zeroconf.py", line 1017 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00001d54 (most recent call first):
  File "zeroconf.py", line 946 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00000424 (most recent call first):
  File "threading.py", line 297 in wait
  File "threading.py", line 549 in wait
  File "D:\Programme\Cura\Ultimaker Cura 3.2\plugins\UM3NetworkPrinting\NetworkPrinterOutputDevicePlugin.py", line 330 in _handleOnServiceChangedRequests
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00004770 (most recent call first):
  File "D:\Programme\Cura\Ultimaker Cura 3.2\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Current thread 0x000041ac (most recent call first):
  File "X:\3.2\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 221 in _logInfoWidget
  File "X:\3.2\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 88 in _createDialog
  File "X:\3.2\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 75 in __init__
  File "X:\3.2\build\inst\bin\cura_app.py", line 74 in exceptHook
  File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 243 in exec_
  File "X:\3.2\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 737 in run
  File "X:\3.2\build\inst\bin\cura_app.py", line 98 in <module>
  File "Console.py", line 24 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
```
`

**Comment by fieldOfView** [comment]
Please try this newer version of the plugin (until the release of the non-beta version of Cura 3.2 this week, at which point you can use the Plugin Browser to install the same version):

http://files.fieldofview.com/temp/OctoPrintPlugin.curaplugin

Drag and drop the curaplugin file onto the running Cura application, and then restart Cura.
